-- COPY DAN JALANKAN SCRIPT INI DI MENU "SQL EDITOR" DI SUPABASE

-- 1. Buat tabel kas_sosial
create table public.kas_sosial (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  tanggal date not null,
  jenis text not null, -- 'masuk' atau 'keluar'
  keterangan text not null,
  nominal numeric not null,
  constraint kas_sosial_pkey primary key (id)
);

-- 2. Aktifkan Row Level Security (RLS)
alter table public.kas_sosial enable row level security;

-- 3. Beri akses penuh (Insert & Select) untuk akses dari public/anon client
-- (Ini digunakan agar aplikasi bisa dipakai tanpa login. Sangat cocok untuk app internal ringan).
create policy "Izinkan siapa saja untuk membaca"
on public.kas_sosial
for select
to public
using (true);

create policy "Izinkan siapa saja untuk menambah"
on public.kas_sosial
for insert
to public
with check (true);
