-- COPY DAN JALANKAN SCRIPT INI DI MENU "SQL EDITOR" DI SUPABASE
create table if not exists public.karyawan (
    id bigint generated by default as identity primary key,
    nama text not null,
    created_at timestamp with time zone default now()
);
create table if not exists public.iuran_bulanan (
    id bigint generated by default as identity primary key,
    karyawan_id bigint not null references public.karyawan(id) on delete cascade,
    bulan_tahun varchar(7) not null,
    nominal numeric not null default 20000,
    created_at timestamp with time zone default now(),
    unique(karyawan_id, bulan_tahun)
);
create table if not exists public.kas_sosial (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  tanggal date not null,
  jenis text not null,
  keterangan text not null,
  nominal numeric not null
);
alter table public.karyawan enable row level security;
alter table public.iuran_bulanan enable row level security;
alter table public.kas_sosial enable row level security;
create policy "Public Access Karyawan" on public.karyawan for all to public using (true) with check (true);
create policy "Public Access Iuran" on public.iuran_bulanan for all to public using (true) with check (true);
create policy "Public Access Kas" on public.kas_sosial for all to public using (true) with check (true);
